In [1]:
# Import required libraries for data manipulation and numerical operations
import pandas as pd
import numpy as np

In [54]:
# Task 1: Create Project dataframe containing project ID, project name, cost, and status
project_df = pd.DataFrame({
    'ID': ['A001','A002','A003','A004','A005',
           'A002','A005','A003','A001','A003',
           'A001','A004','A004','A005'],
    'Project': ['Project 1','Project 2','Project 3','Project 4','Project 5',
                'Project 6','Project 7','Project 8','Project 9','Project 10',
                'Project 11','Project 12','Project 13','Project 14'],
    'Cost': [102000,200000,450000,550000,np.nan,
             680000,400000,350000,np.nan,300000,
             2000000,1000000,3000000,200000],
    'Status': ['Finished','Ongoing','Finished','Ongoing','Finished',
               'Failed','Finished','Failed','Ongoing','Finished',
               'Failed','Ongoing','Finished','Finished']
})

In [55]:
# Display Project dataframe
project_df

      ID     Project       Cost    Status
0   A001   Project 1   102000.0  Finished
1   A002   Project 2   200000.0   Ongoing
2   A003   Project 3   450000.0  Finished
3   A004   Project 4   550000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [57]:
# Task 1: Create Employee dataframe containing employee details
employee_df = pd.DataFrame({
    'ID': ['A001','A002','A003','A004','A005'],
    'Name': ['John Alter','Alice Luxumberg','Tom Sabestine','Nina Adgra','Amy Johny'],
    'Gender': ['M','F','M','F','F'],
    'City': ['Paris','London','Berlin','Newyork','Madrid'],
    'Age': [25,27,29,31,30]
})

In [58]:
# Display Employee dataframe
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [59]:
# Task 1: Create Designation dataframe containing employee designation levels
designation_df = pd.DataFrame({
    'ID': ['A001','A002','A003','A004','A005'],
    'Designation Level': [2,2,3,2,3]
})

In [7]:
# Display Designation dataframe
designation_df

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [60]:
project_df.to_csv('project.csv', index=False)
employee_df.to_csv('employee.csv', index=False)
designation_df.to_csv('designation.csv', index=False)

In [61]:
project_df = pd.read_csv('project.csv')
project_df

      ID     Project       Cost    Status
0   A001   Project 1   102000.0  Finished
1   A002   Project 2   200000.0   Ongoing
2   A003   Project 3   450000.0  Finished
3   A004   Project 4   550000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [62]:
project_df.isnull().sum()

ID         0
Project    0
Cost       2
Status     0
dtype: int64

In [63]:
# Task 2: Replace missing project cost values using average cost
project_df['Cost'] = project_df['Cost'].fillna(
    project_df['Cost'].expanding().mean()
)

In [64]:
project_df

      ID     Project          Cost    Status
0   A001   Project 1  1.020000e+05  Finished
1   A002   Project 2  2.000000e+05   Ongoing
2   A003   Project 3  4.500000e+05  Finished
3   A004   Project 4  5.500000e+05   Ongoing
4   A005   Project 5  3.255000e+05  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  3.902857e+05   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [65]:
project_df.to_csv('project.csv', index=False)

In [66]:
employee_df = pd.read_csv('employee.csv')
employee_df

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [67]:
# Task 3: Split Name column into First Name and Last Name and remove original Name column
employee_df[['First Name', 'Last Name']] = employee_df['Name'].str.split(' ', expand=True)

In [68]:
employee_df

     ID             Name Gender     City  Age First Name  Last Name
0  A001       John Alter      M    Paris   25       John      Alter
1  A002  Alice Luxumberg      F   London   27      Alice  Luxumberg
2  A003    Tom Sabestine      M   Berlin   29        Tom  Sabestine
3  A004       Nina Adgra      F  Newyork   31       Nina      Adgra
4  A005        Amy Johny      F   Madrid   30        Amy      Johny

In [69]:
# Task 3: Split Name column into First Name and Last Name and remove original Name column
employee_df.drop(columns=['Name'], inplace=True)
employee_df

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [70]:
employee_df.to_csv('employee.csv', index=False)

In [73]:
project_df = pd.read_csv('project.csv')
employee_df = pd.read_csv('employee.csv')
designation_df = pd.read_csv('designation.csv')

In [74]:
project_df.head(), employee_df.head(), designation_df.head()

(     ID    Project      Cost    Status
 0  A001  Project 1  102000.0  Finished
 1  A002  Project 2  200000.0   Ongoing
 2  A003  Project 3  450000.0  Finished
 3  A004  Project 4  550000.0   Ongoing
 4  A005  Project 5  325500.0  Finished,
      ID Gender     City  Age First Name  Last Name
 0  A001      M    Paris   25       John      Alter
 1  A002      F   London   27      Alice  Luxumberg
 2  A003      M   Berlin   29        Tom  Sabestine
 3  A004      F  Newyork   31       Nina      Adgra
 4  A005      F   Madrid   30        Amy      Johny,
      ID  Designation Level
 0  A001                  2
 1  A002                  2
 2  A003                  3
 3  A004                  2
 4  A005                  3)

In [75]:
merged_df = pd.merge(project_df, employee_df, on='ID', how='left')
merged_df

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name
0,A001,Project 1,1.020000e+05,Finished,M,Paris,25,John,Alter
1,A002,Project 2,2.000000e+05,Ongoing,F,London,27,Alice,Luxumberg
2,A003,Project 3,4.500000e+05,Finished,M,Berlin,29,Tom,Sabestine
3,A004,Project 4,5.500000e+05,Ongoing,F,Newyork,31,Nina,Adgra
4,A005,Project 5,3.255000e+05,Finished,F,Madrid,30,Amy,Johny
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine
8,A001,Project 9,3.902857e+05,Ongoing,M,Paris,25,John,Alter
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny

In [76]:
# Task 4: Merge Project, Employee, and Designation dataframes into a single dataframe named Final
final_df = pd.merge(merged_df, designation_df, on='ID', how='left')
final_df

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1.020000e+05,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2.000000e+05,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4.500000e+05,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5.500000e+05,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3.255000e+05,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,3.902857e+05,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3

In [77]:
final_df.to_csv('final_df.csv', index=False)

In [78]:
final_df = pd.read_csv('final_df.csv')
final_df

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1.020000e+05,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2.000000e+05,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4.500000e+05,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5.500000e+05,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3.255000e+05,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,3.902857e+05,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3

In [79]:
# Task 5: Add Bonus column giving 5% bonus for employees who finished projects
final_df['Bonus'] = np.where(
    final_df['Status'] == 'Finished',
    final_df['Cost'] * 0.05,
    0
)

In [80]:
final_df[['ID', 'Project', 'Cost', 'Status', 'Bonus']].head()

     ID    Project      Cost    Status    Bonus
0  A001  Project 1  102000.0  Finished   5100.0
1  A002  Project 2  200000.0   Ongoing      0.0
2  A003  Project 3  450000.0  Finished  22500.0
3  A004  Project 4  550000.0   Ongoing      0.0
4  A005  Project 5  325500.0  Finished  16275.0

In [81]:
final_df.to_csv('final_df.csv', index=False)

In [82]:
final_df = pd.read_csv('final_df.csv')
final_df[['ID', 'Status', 'Designation Level']].head()

     ID    Status  Designation Level
0  A001  Finished                  2
1  A002   Ongoing                  2
2  A003  Finished                  3
3  A004   Ongoing                  2
4  A005  Finished                  3

In [83]:
# Task 6:
# Reducing designation level by 1 for employees whose project status is Failed
final_df.loc[final_df['Status'] == 'Failed', 'Designation Level'] -= 1

In [84]:
final_df[['ID', 'Status', 'Designation Level']].head(10)

     ID    Status  Designation Level
0  A001  Finished                  2
1  A002   Ongoing                  2
2  A003  Finished                  3
3  A004   Ongoing                  2
4  A005  Finished                  3
5  A002    Failed                  1
6  A005  Finished                  3
7  A003    Failed                  2
8  A001   Ongoing                  2
9  A003  Finished                  3

In [85]:
# Removing employees whose designation level is above 4 after demotion
final_df = final_df[
    ~((final_df['Status'] == 'Failed') & (final_df['Designation Level'] > 4))
]

In [86]:
final_df.to_csv('final_df.csv', index=False)

In [87]:
final_df = pd.read_csv('final_df.csv')
final_df[['First Name', 'Gender']].head()

  First Name Gender
0       John      M
1      Alice      F
2        Tom      M
3       Nina      F
4        Amy      F

In [88]:
# Task 7:
# Adding title (Mr./Mrs.) to First Name based on Gender
# Dropping the Gender column after modification
final_df['First Name'] = np.where(
    final_df['Gender'] == 'M',
    'Mr. ' + final_df['First Name'],
    'Mrs. ' + final_df['First Name']
)

In [89]:
final_df[['First Name', 'Gender']].head()

   First Name Gender
0    Mr. John      M
1  Mrs. Alice      F
2     Mr. Tom      M
3   Mrs. Nina      F
4    Mrs. Amy      F

In [90]:
final_df.drop(columns=['Gender'], inplace=True)
final_df.head()

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,102000.0,Finished,Paris,25,Mr. John,Alter,2,5100.0
1,A002,Project 2,200000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
2,A003,Project 3,450000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,22500.0
3,A004,Project 4,550000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
4,A005,Project 5,325500.0,Finished,Madrid,30,Mrs. Amy,Johny,3,16275.0

In [91]:
final_df.to_csv('final_df.csv', index=False)

In [92]:
final_df = pd.read_csv('final_df.csv')
final_df.head()

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,102000.0,Finished,Paris,25,Mr. John,Alter,2,5100.0
1,A002,Project 2,200000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
2,A003,Project 3,450000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,22500.0
3,A004,Project 4,550000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
4,A005,Project 5,325500.0,Finished,Madrid,30,Mrs. Amy,Johny,3,16275.0

In [93]:
total_cost_df = (
    final_df
    .groupby(['ID', 'First Name'])['Cost']
    .sum()
    .reset_index()
)

In [94]:
total_cost_df

     ID  First Name          Cost
0  A001    Mr. John  2.492286e+06
1  A002  Mrs. Alice  8.800000e+05
2  A003     Mr. Tom  1.100000e+06
3  A004   Mrs. Nina  4.550000e+06
4  A005    Mrs. Amy  9.255000e+05

In [95]:
total_cost_df.to_csv('total_project_cost.csv', index=False)

In [96]:
final_df[['Age', 'Designation Level']].head()

   Age  Designation Level
0   25                  2
1   27                  2
2   29                  3
3   31                  2
4   30                  3

In [97]:
# Task 8:
# Promoting employees by increasing designation level by 1 if age is greater than 29
final_df['Designation Level'] = final_df.apply(
    lambda x: x['Designation Level'] + 1 if x['Age'] > 29 else x['Designation Level'],
    axis=1
)

In [98]:
final_df[['Age', 'Designation Level']]

    Age  Designation Level
0    25                  2
1    27                  2
2    29                  3
3    31                  3
4    30                  4
5    27                  1
6    30                  4
7    29                  2
8    25                  2
9    29                  3
10   25                  1
11   31                  3
12   31                  3
13   30                  4

In [99]:
# Task 9:
# Calculating total project cost for each employee
# Creating a new dataframe TotalProjCost with ID, First Name, and Total Cost
TotalProjCost = (
    final_df
    .groupby(['ID', 'First Name'])['Cost']
    .sum()
    .reset_index()
)

TotalProjCost.rename(columns={'Cost': 'Total Cost'}, inplace=True)
TotalProjCost

     ID  First Name    Total Cost
0  A001    Mr. John  2.492286e+06
1  A002  Mrs. Alice  8.800000e+05
2  A003     Mr. Tom  1.100000e+06
3  A004   Mrs. Nina  4.550000e+06
4  A005    Mrs. Amy  9.255000e+05

In [100]:
# Task 10:
# Displaying employee details where city name contains the letter 'o'
final_df[final_df['City'].str.contains('o', case=False, na=False)]

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
1,A002,Project 2,200000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
3,A004,Project 4,550000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000.0